
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 31 00:51:28 CST 2015
//----------------------------------------------------

package sumadoraarbol;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESTA = 3;
  public static final int error = 1;
  public static final int SUMA = 2;
  public static final int PCOMA = 4;
  public static final int DECIMAL = 5;
  public static final int EOF = 0;
}

