
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 17 01:23:18 CST 2014
//----------------------------------------------------

package sumadoraarbol;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESTA = 3;
  public static final int error = 1;
  public static final int SUMA = 2;
  public static final int PCOMA = 4;
  public static final int DECIMAL = 5;
  public static final int EOF = 0;
}

